permissionset 80130 Novem_PMP
{
    Assignable = true;
    Permissions = tabledata I9G_ThirdPartyLogisticSetup = RIMD,
        tabledata "Dimension Set Entry" = RIMD,
        table I9G_ThirdPartyLogisticSetup = X,
        report I9G_DeliveryOrder3PL = X,
        report I9G_TaxInvoice3PL = X,
        codeunit I9G_BatchCreatePO = X,
        codeunit I9G_BindSubscription = X,
        codeunit I9G_PostCreditMm = X,
        codeunit I9G_PostInvoice = X,
        codeunit I9G_PostReceive = X,
        codeunit I9G_PostShipment = X,
        codeunit I9G_ThirdPartyLogisticCU = X,
        codeunit I9G_UndoReceipt = X,
        codeunit I9G_UndoShipment = X,
        page I9G_ThirdPartyLogisticSetup = X,
        report I9G_PostedSalesCreditNote3PL = X,
        codeunit I9G_BatchCreateSO = X,
        codeunit I9G_CreatePurchWhseReceipt = X,
        codeunit I9G_CreateSalesWhseReceipt = X,
        codeunit I9G_CreateSalesWhseShipAndPick = X,
        codeunit I9G_CreateTransWhseShipAndPick = X,
        report "PMP Novem Sales Report" = X,
        report I9G_AssemblyWaybill3PL = X,
        report I9G_PostedInvWaybillLabel3PL = X,
        report I9G_TOWaybillLabel3PL = X,
        report I9G_WaybillLabel3PL = X,
        report UpdatePostedInvoicePMP = X,
        codeunit I9G_PostSalesDocument = X,
        report ProcessAndDataControl = X,
        page "PMP Bin Content For Novem" = X,
        report "3PLSalesOrderMatching" = X,
        report InventoryMatching3PL = X,
        report I9G_NovemCreditNote3PL = X,
        report I9G_NovemTaxInvoice3PL = X,
        page ViewBinContent3PL = X,
        report I9G_Novem3PLSalesInvoiceLines = X,
        report I9G_Novem3PLSalesInvoiceS = X,
        codeunit I9G_DimensionSetCleanupCU = X;
}